### ISSUE TITLE
The Creaking dies when hit

### ISSUE THREAD

**Issue by AcaGamer5** [danbrown/palegardenbackport#2]
The Creaking dies upon being hit (due to it having 1 HP and no damage immunities), this could also prevent resin clumps from spawning.

**Comment by AcaGamer5** [comment]
Just as a sidenote, yes, there is a Creaking Heart nearby. It was placed BEFORE the Creaking was spawned in.

**Comment by danbrown** [comment]
Hello! Was the Creaking spawned with a spawn egg? If yes, this is the desired behavior. Only Creakings spawned with a Creaking Heart are immune to damage.

**Comment by AcaGamer5** [comment]
Oh yeah, it was. Thanks for clarifying, I was very confused at the moment since I wanted to test how resin clumps form haha

**Comment by danbrown** [comment]
No problem! I'm closing this issue then, if you find another bug let me know!
